name: "compute-baseline"
on:
  workflow_dispatch:
  # schedule:
  # - cron: "30 11,12,13,14 * * *"
  
permissions:
  contents: write  
  
jobs:
  compute-baseline:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
        
    - name: Setup R
      uses: r-lib/actions/setup-r@v2 
      with:
        r-version: '4.2.3'
      
    - name: Compute baseline
      run: |
        Rscript ./nowcasting/run_baseline.R

    # - name: Create Pull Request
    #   id: cpr
    #   uses: peter-evans/create-pull-request@v7
    #   with:
    #     token: ${{ secrets.SARI_ML }}
    #     commit-message: Update baseline
    #     committer: GitHub <noreply@github.com>
    #     author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
    #     signoff: false
    #     branch: compute-baseline
    #     delete-branch: true
    #     title: 'Compute baseline'
    #     body: |
    #       Compute baseline
    #     labels: |
    #       automated pr
    #       automerge
          
    # - name: Automerge check
    #   uses: "pascalgn/automerge-action@v0.16.4"
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.SARI_ML }}
    #     MERGE_LABELS: "automerge"

    - name: Commit files
      env:
        AUTH: ${{ secrets.SARI_ML }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git remote rm origin
        git remote add origin https://${AUTH}@github.com/dwolffram/SARI-ML.git > /dev/null 2>&1
        git pull origin main
        git add --all
        git commit --allow-empty -m "Compute baseline"
        
    - name: Push changes
      run: |
        git push --quiet --set-upstream origin HEAD:main
        echo "pushed to github"
